# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'States.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_States(object):
    def setupUi(self, States):
        States.setObjectName("States")
        States.resize(935, 529)
        self.tabWidget = QtWidgets.QTabWidget(States)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.States_1 = QtWidgets.QWidget()
        self.States_1.setObjectName("States_1")
        self.label_17 = QtWidgets.QLabel(self.States_1)
        self.label_17.setGeometry(QtCore.QRect(300, 420, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.States_1)
        self.label_14.setGeometry(QtCore.QRect(300, 270, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.States_1)
        self.label_16.setGeometry(QtCore.QRect(300, 370, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_2 = QtWidgets.QLabel(self.States_1)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(self.States_1)
        self.label_10.setGeometry(QtCore.QRect(30, 420, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.States_1)
        self.label_11.setGeometry(QtCore.QRect(300, 120, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label = QtWidgets.QLabel(self.States_1)
        self.label.setGeometry(QtCore.QRect(30, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.States_1)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_15 = QtWidgets.QLabel(self.States_1)
        self.label_15.setGeometry(QtCore.QRect(300, 320, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(self.States_1)
        self.label_12.setGeometry(QtCore.QRect(300, 170, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.States_1)
        self.label_13.setGeometry(QtCore.QRect(300, 220, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_6 = QtWidgets.QLabel(self.States_1)
        self.label_6.setGeometry(QtCore.QRect(30, 220, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.States_1)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.States_1)
        self.label_7.setGeometry(QtCore.QRect(30, 270, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.States_1)
        self.label_8.setGeometry(QtCore.QRect(30, 320, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.States_1)
        self.label_3.setGeometry(QtCore.QRect(300, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.States_1)
        self.label_9.setGeometry(QtCore.QRect(30, 370, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_18 = QtWidgets.QLabel(self.States_1)
        self.label_18.setGeometry(QtCore.QRect(440, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.listView = QtWidgets.QListView(self.States_1)
        self.listView.setGeometry(QtCore.QRect(440, 60, 481, 211))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(self.States_1)
        self.pushButton.setGeometry(QtCore.QRect(450, 290, 461, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.States_1)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 360, 461, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.States_1)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 430, 461, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.States_1, "")
        self.User_defined_variables = QtWidgets.QWidget()
        self.User_defined_variables.setObjectName("User_defined_variables")
        self.comboBox = QtWidgets.QComboBox(self.User_defined_variables)
        self.comboBox.setGeometry(QtCore.QRect(50, 30, 791, 23))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.listView_2 = QtWidgets.QListView(self.User_defined_variables)
        self.listView_2.setGeometry(QtCore.QRect(50, 80, 791, 351))
        self.listView_2.setObjectName("listView_2")
        self.tabWidget.addTab(self.User_defined_variables, "")

        self.retranslateUi(States)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(States)

    def retranslateUi(self, States):
        _translate = QtCore.QCoreApplication.translate
        States.setWindowTitle(_translate("States", "States"))
        self.label_17.setText(_translate("States", "Gripper: 1.0"))
        self.label_14.setText(_translate("States", "Roll: 1.0"))
        self.label_16.setText(_translate("States", "Pitch: 1.0"))
        self.label_2.setText(_translate("States", "Left Arm"))
        self.label_10.setText(_translate("States", "Gripper: 1.0"))
        self.label_11.setText(_translate("States", "Pos x: 10.0"))
        self.label.setText(_translate("States", "Current States"))
        self.label_5.setText(_translate("States", "Pos y: 10.0"))
        self.label_15.setText(_translate("States", "Yaw: 1.0"))
        self.label_12.setText(_translate("States", "Pos y: 10.0"))
        self.label_13.setText(_translate("States", "Pos z: 10.0"))
        self.label_6.setText(_translate("States", "Pos z: 10.0"))
        self.label_4.setText(_translate("States", "Pos x: 10.0"))
        self.label_7.setText(_translate("States", "Roll: 1.0"))
        self.label_8.setText(_translate("States", "Pitch: 1.0"))
        self.label_3.setText(_translate("States", "Right Arm"))
        self.label_9.setText(_translate("States", "Yaw: 1.0"))
        self.label_18.setText(_translate("States", "Saved States"))
        self.pushButton.setText(_translate("States", "Delete State"))
        self.pushButton_2.setText(_translate("States", "Save State"))
        self.pushButton_3.setText(_translate("States", "Add to Task Planner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.States_1), _translate("States", "States"))
        self.comboBox.setItemText(0, _translate("States", "State_ip"))
        self.comboBox.setItemText(1, _translate("States", "robot_name"))
        self.comboBox.setItemText(2, _translate("States", "Joint_State"))
        self.comboBox.setItemText(3, _translate("States", "End_Effector_Force"))
        self.comboBox.setItemText(4, _translate("States", "Hole_Select"))
        self.comboBox.setItemText(5, _translate("States", "App"))
        self.comboBox.setItemText(6, _translate("States", "Main_Window"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.User_defined_variables), _translate("States", "User_defined_variables"))

