# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task_Planner.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Task_Planner(object):
    def setupUi(self, Task_Planner):
        Task_Planner.setObjectName("Task_Planner")
        Task_Planner.resize(770, 765)
        self.listWidget = QtWidgets.QListWidget(Task_Planner)
        self.listWidget.setGeometry(QtCore.QRect(430, 60, 256, 331))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label = QtWidgets.QLabel(Task_Planner)
        self.label.setGeometry(QtCore.QRect(430, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Task_Planner)
        self.label_2.setGeometry(QtCore.QRect(420, 410, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listView = QtWidgets.QListView(Task_Planner)
        self.listView.setGeometry(QtCore.QRect(430, 460, 256, 192))
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(Task_Planner)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listView_2 = QtWidgets.QListView(Task_Planner)
        self.listView_2.setGeometry(QtCore.QRect(30, 60, 256, 341))
        self.listView_2.setObjectName("listView_2")
        self.pushButton = QtWidgets.QPushButton(Task_Planner)
        self.pushButton.setGeometry(QtCore.QRect(40, 430, 241, 41))
        self.pushButton.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;}\"\n"
"                                           \"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\"\n"
"                                           \"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Task_Planner)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 490, 241, 41))
        self.pushButton_2.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;}\"\n"
"                                           \"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\"\n"
"                                           \"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Task_Planner)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 550, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;}\"\n"
"                                           \"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\"\n"
"                                           \"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Task_Planner)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 610, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;}\"\n"
"                                           \"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\"\n"
"                                           \"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Task_Planner)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 670, 241, 41))
        self.pushButton_5.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;}\"\n"
"                                           \"QPushButton:hover{background-color:rgb(229, 241, 251); color: black;}\"\n"
"                                           \"QPushButton:pressed{background-color:rgb(204, 228, 247);border-style: inset;}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Task_Planner)
        QtCore.QMetaObject.connectSlotsByName(Task_Planner)

    def retranslateUi(self, Task_Planner):
        _translate = QtCore.QCoreApplication.translate
        Task_Planner.setWindowTitle(_translate("Task_Planner", "Task_Planner"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Task_Planner", "L0_dual_jp_move_safe_relate"))
        item = self.listWidget.item(1)
        item.setText(_translate("Task_Planner", "L0_dual_set_gripper"))
        item = self.listWidget.item(2)
        item.setText(_translate("Task_Planner", "L0_dual_task_move_safe_relate"))
        item = self.listWidget.item(3)
        item.setText(_translate("Task_Planner", "L0_single_set_gripper"))
        item = self.listWidget.item(4)
        item.setText(_translate("Task_Planner", "L0_single_task_move_safe"))
        item = self.listWidget.item(5)
        item.setText(_translate("Task_Planner", "L0_upper_jp_move_safe"))
        item = self.listWidget.item(6)
        item.setText(_translate("Task_Planner", "L1_dual_flip_case_V1_hardcode"))
        item = self.listWidget.item(7)
        item.setText(_translate("Task_Planner", "L1_dual_mate_case_V1_hardcode"))
        item = self.listWidget.item(8)
        item.setText(_translate("Task_Planner", "L1_dual_pick_case_V1_hardcode"))
        item = self.listWidget.item(9)
        item.setText(_translate("Task_Planner", "L1_insert_bolt_V1_hardcode"))
        item = self.listWidget.item(10)
        item.setText(_translate("Task_Planner", "L1_insert_bolt_V2_BIPA"))
        item = self.listWidget.item(11)
        item.setText(_translate("Task_Planner", "L1_mate_case_V2_birdview"))
        item = self.listWidget.item(12)
        item.setText(_translate("Task_Planner", "L1_pick_bolt_V1_hardcode"))
        item = self.listWidget.item(13)
        item.setText(_translate("Task_Planner", "L1_pick_case_V2_birdview"))
        item = self.listWidget.item(14)
        item.setText(_translate("Task_Planner", "L1_screw_V1_hardcode"))
        item = self.listWidget.item(15)
        item.setText(_translate("Task_Planner", "L1_screw_V2_BIPA"))
        item = self.listWidget.item(16)
        item.setText(_translate("Task_Planner", "L1_single_task_move_relate"))
        item = self.listWidget.item(17)
        item.setText(_translate("Task_Planner", "L2_rightarm_insert_leftarm_screw"))
        item = self.listWidget.item(18)
        item.setText(_translate("Task_Planner", "L3_pick_matecase_pickbolt_insert_screw"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Task_Planner", "Action Library"))
        self.label_2.setText(_translate("Task_Planner", "User Defined Action"))
        self.label_3.setText(_translate("Task_Planner", "Task Planner"))
        self.pushButton.setText(_translate("Task_Planner", "Delete Task"))
        self.pushButton_2.setText(_translate("Task_Planner", "Save as Action"))
        self.pushButton_3.setText(_translate("Task_Planner", "Emergency Stop"))
        self.pushButton_4.setText(_translate("Task_Planner", "Execute"))
        self.pushButton_5.setText(_translate("Task_Planner", "Add to Task Planner"))

